[dbus]
session = true
system = false

[http]
listen = "0.0.0.0:9110"

[http.tls]
cert = "/etc/node_exporter/mariatu.crt"
key = "/etc/node_exporter/mariatu.key"

[http.tls.verify]
ca = "/etc/node_exporter/CA.crt"
